
version: "3.9"

services:
  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    networks:
      - auth_network
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: auth_db
        POSTGRES_USER: joaountura
        POSTGRES_PASSWORD: joaountura@dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joaountura -d auth_db"]
      interval: 5s
      retries: 20
      timeout: 5s
      start_period: 10s

  redis_auth:
    image: redis:8.0.3
    container_name: redis_auth
    networks:
      - auth_network
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 20
      timeout: 5s
      start_period: 5s

  spring:
    image: joaountura/auth-project:latest
    container_name: spring
    networks:
      - auth_network
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_REDIS_HOST: redis_auth
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth_postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: joaountura
      SPRING_DATASOURCE_PASSWORD: joaountura@dev
      LOGGING_FILE_NAME: /logs/app.log
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      auth_postgres:
        condition: service_healthy
      redis_auth:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 20
      timeout: 5s
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    networks:
      - auth_network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      retries: 10
      timeout: 10s
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    networks:
      - auth_network
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      retries: 10
      timeout: 10s
      start_period: 60s

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    networks:
      - auth_network
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs:/usr/share/logstash/logs:ro
    ports:
      - "5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 30s
      retries: 10
      timeout: 10s
      start_period: 60s

  kong:
    image: kong:3.6
    container_name: kong
    networks:
      - auth_network
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:80, 0.0.0.0:443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
      - "8001:8001"
    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml:ro
    depends_on:
      spring:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kong health"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 30s

volumes:
  postgres_data:
    driver: local
  es_data:
    driver: local
  kibana_data:
    driver: local

networks:
  auth_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16