services:
  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: joaountura
      POSTGRES_PASSWORD: joaountura@dev
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis_auth:
    image: redis:8.0.3
    container_name: redis_auth
    ports:
      - "6380:6379"
    restart: unless-stopped

  spring:
    image: joaountura/auth-project:latest
    container_name: spring
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
        SPRING_REDIS_HOST: redis_auth
        SPRING_REDIS_PORT: 6380
        SPRING_DATASOURCE_URL: jdbc:postgresql://auth_postgres:5432/auth_db
        LOGGING_FILE_NAME: /logs/app.log
    

    depends_on:
      - auth_postgres
      - redis_auth

  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"   
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:80, 0.0.0.0:443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"

    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
      - "8001:8001"

    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
      image: docker.elastic.co/kibana/kibana:8.14.0
      container_name: kibana
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      volumes:
        - kibana_data:/usr/share/kibana/data
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

  logstash:
      image: docker.elastic.co/logstash/logstash:8.14.0
      container_name: logstash
      volumes:
        - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./logs:/usr/share/logstash/logs
      ports:
        - "5000:5000"
      depends_on:
        - elasticsearch


volumes:
  postgres_data:
  es_data:
  kibana_data:



